### ISSUE TITLE
Make the extension translatable

### ISSUE THREAD

**Issue by dev-allinappli** [Aulig/webtoapp-wordpress#1]
The extension can't be translated as it lacks the WordPress translation functions https://developer.wordpress.com/themes/i18n/. Other documentation: https://daext.com/blog/how-to-make-a-wordpress-plugin-translatable/

**Comment by Aulig** [comment]
Thanks for the issue! Are you looking to create a pull request for this?

Based on the documentation you shared it doesn't look too complicated, so I could probably do it too with my limited PHP abilities :)

**Comment by dev-allinappli** [comment]
As you wish. We could do it next week. But actually it's just about adding _e() around all chains which is pretty easy.

**Comment by Aulig** [comment]
If you can find time for it, it'd be much appreciated! If not, I'll get to it eventually, no problem. I just have a lot of work on my plate at the moment 😅

**Comment by iassadki** [comment]
Hello, we have finished the task. All the extension are translatable. I have changed some little things in the code to respect the Wordpress Documentation for the traduction.

I have changed the majority of the double quotes, replaced them by simple quotes, to support the plugin translate

**Comment by iassadki** [comment]
Hello, we have finished the job.

All the substrings of extension are translatable. I have changed some little things in the code to respect the Wordpress Documentation for the translation.

For example, I have changed the majority of the double quotes, replaced them by simple quotes

### Changes of the substrings in an **html tag**

**OLD**
```php
$out .= "<h3 class='title'>New Page Publish Notification</h3>";
```
**NEW**
```php
$out .= '<h3 class="title">' . esc_html__('Push Notifications', 'webtoapp-design') . '</h3>'; 
```

### Changes of the attributes in an **html tag**

**OLD**
```php
$out .= "<input name='message' class='form-control' placeholder='Message (optional)' id='message' type='text' >";
```

**NEW**
```php
$out .= '<input name="message" class="form-control" placeholder="' . esc_attr__('Message (optional)', 'webtoapp-design') . '" id="message" type="text" >';
```

### And for the JS, here is the changes : 

**OLD**
```php
$out .= "title: 'Choose or Upload Media',";
```
**NEW**
```php
$out .= "title: '" . esc_js(__('Choose or Upload Media', 'webtoapp-design')) . "',";
```

**OLD**
```php
$out .= "text: 'Use this media'";
```

**NEW**
```php
$out .= "text: '" . esc_js(__('Use this media', 'webtoapp-design')) . "'";
```

I'll make the changes directly in the project/

**Comment by Aulig** [comment]
Sounds good! In your first example it looks like the text changed from "New Page Publish Notification" to "Push Notifications" - but maybe that was just a copy paste mistake. Feel free to send the changes as a PR and I'll review it asap :)

**Comment by Aulig** [comment]
Thanks for your work @iassadki ! I've merged your pull requests and pushed out a new version.
